### ISSUE TITLE
caffe cpu 模式 编译出现结果全0或全1

### ISSUE THREAD

**Issue by shuangliyue** [shenwei1231/caffe-DeepRegressionForests#1]
gpu上预测没问题，但是同样的模型，用cpu预测输出的结果不是0就是1

**Comment by shenwei1231** [comment]
Did you retrain the model in CPU phase or directly test the model trained in GPU phase?

**Comment by shenwei1231** [comment]
If you retrained the model in CPU phase, you need to train it much longer. We checked the CPU code and do not find any problem.

**Comment by shuangliyue** [comment]
Yeah,I have retrained in CPU mode, but tested in CPU mode remains the problem.The output is wrong. When trained in GPU mode and tested in GPU mode,the output is normal.
发自网易邮箱大师
在2018年12月24日 05:31，Wei Shen 写道： If you retrained the model in CPU phase, you need to train it much longer. We checked the CPU code and do not find any problem.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/shenwei1231/caffe-DeepRegressionForests","title":"shenwei1231/caffe-DeepRegressionForests","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/shenwei1231/caffe-DeepRegressionForests"}},"updates":{"snippets":[{"icon":"PERSON","message":"@shenwei1231 in #1: If you retrained the model in CPU phase, you need to train it much longer. We checked the CPU code and do not find any problem."}],"action":{"name":"View Issue","url":"https://github.com/shenwei1231/caffe-DeepRegressionForests/issues/1#issuecomment-449664400"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/shenwei1231/caffe-DeepRegressionForests/issues/1#issuecomment-449664400",
"url": "https://github.com/shenwei1231/caffe-DeepRegressionForests/issues/1#issuecomment-449664400",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by shuangliyue** [comment]
@shenwei1231 Yeah,I have retrained in CPU mode, but tested in CPU mode remains the problem.The output is wrong. When trained in GPU mode and tested in GPU mode,the output is normal.

**Comment by shuangliyue** [comment]
could you provide a model trained in CPU mode so that  i can see if it’s a training problem or a test problem. Because we tested on the same model and it worked well in GPU mode，but it didn't work in CPU mode. And i have a question whether the model trained in GPU mode can work or not  in CPU mode.

**Comment by shenwei1231** [comment]
The CPU code is much slower than GPU code. I guess leaf nodes have not been updated in your training. You can use the model trained in GPU phase and test it in CPU phase.

**Comment by shuangliyue** [comment]
@shenwei1231 
train in GPU,test in GPU,the output is correct
train in GPU,test in CPU,the output is wrong
train in CPU,test in CPU,the output is wrong
train in CPU,test in GPU,the output is correct
So I guess there is something wrong in neural_decision_reg_forest_layer.cpp

**Comment by shenwei1231** [comment]
We have updated the CPU code. Now the problem is solved. Thanks.

**Comment by shuangliyue** [comment]
That's great!!! Thx.

**Comment by MoonBunnyZZZ** [comment]
> gpu上预测没问题，但是同样的模型，用cpu预测输出的结果不是0就是1

@shuangliyue 不知道为什么,1)CPU模式下编译到test有两个error,2)pycaffe编译过了,无法import caffe
做了许多尝试都无效.你怎么编译通过的?
